export const HEADER_ACTIVE = 'HEADER_ACTIVE'
export const CHANGE_COMMUNITY_ITEM = 'CHANGE_COMMUNITY_ITEM'
export const CHANGE_SHOPPING_ITEM = 'CHANGE_SHOPPING_ITEM'
export const FOOTER_ACTIVE = 'FOOTER_ACTIVE'