// 纯redux例子
/*
export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'*/

// 结合react-redux实现
export const ADD_TODO = 'ADD_TODO'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const HEADER_ACTIVE = 'HEADER_ACTIVE'
export const CHANGE_COMMUNITY_ITEM = 'CHANGE_COMMUNITY_ITEM'
export const CHANGE_SHOPPING_ITEM = 'CHANGE_SHOPPING_ITEM'